added --ls option, reformated usage(), added --getopt option

diff --git a/screen-session b/screen-session
--- a/screen-session
+++ b/screen-session
@@ -6,16 +6,23 @@
 # it is necessary to run screen-session.py embedded in other screen session to be able to run it from saved/loaded screen session
 
 rawargument=`screen -Q @sessionname`
-if [ `echo ${rawargument} | grep -c "^This"` -eq 1 ]; then
-    echo "running inside patched Screen session"
-    argument="--current-session "`screen -Q @sessionname | python -c "import sys; print(sys.stdin.read().split('\'',1)[1].rsplit('\'',1)[0].split('.',1)[0])"`
-    #echo $argument $* | xargs screen-session.py $argument $*
-    #screen -m -c /dev/null screen-session.py --wait $argument $*
-    screen -m -c /dev/null screen-session.py $argument $*
+
+screen-session.py --getopt $*
+
+if [ $? -eq 0 ]; then
+    if [ `echo ${rawargument} | grep -c "^This"` -eq 1 ]; then
+        echo "running inside patched Screen session"
+        argument="--current-session "`screen -Q @sessionname | python -c "import sys; print(sys.stdin.read().split('\'',1)[1].rsplit('\'',1)[0].split('.',1)[0])"`
+        #echo $argument $* | xargs screen-session.py $argument $*
+        #screen -m -c /dev/null screen-session.py --wait $argument $*
+        screen -m -c /dev/null screen-session.py $argument $*
+    else
+        echo "not running inside patched Screen, this session cannot be saved properly"
+        argument=""
+        screen-session.py $argument $*
+    fi
 else
-    echo "not running inside patched Screen, this session cannot be saved properly"
-    argument=""
-    ./screen-session.py $argument $*
+    screen-session.py  $*
 fi
 
 
